apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: elasticsearch
    server: {{ .Values.spec.destination.server }}
  project: default

  source:
    chart: elasticsearch
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
  
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
