apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: elasticsearch
    server: {{ .Values.spec.destination.server }}
  project: default

  source:
    chart: elasticsearch
    repoURL: https://helm.elastic.co
    targetRevision: 8.5.1
    helm:
      values: |
        service:
          type: NodePort
          nodePort: 30085
        # Reference: https://github.com/elastic/helm-charts/blob/main/elasticsearch/examples/docker-for-mac/values.yaml
        # Permit co-located instances for solitary minikube virtual machines.
        antiAffinity: "soft"

        # Shrink default JVM heap.
        esJavaOpts: "-Xmx128m -Xms128m"

        # Allocate smaller chunks of memory per pod.
        resources:
          requests:
            cpu: "100m"
            memory: "512M"
          limits:
            cpu: "1000m"
            memory: "512M"

        # Request smaller persistent volumes.
        volumeClaimTemplate:
          accessModes: [ "ReadWriteOnce" ]
          storageClassName: "hostpath"
          resources:
            requests:
              storage: 100M

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
