apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metabase
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://metabase.github.io/metabase
    targetRevision: HEAD
    path: charts/metabase
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: metabase
  syncPolicy:
    automated:
      prune: true
      selfHeal: true