apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 8.0.11
    chart: bitnami/mongodb
    helm:
      values: |
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: mongodb
  syncPolicy:
    syncOptions:
      - CreateNamespace=true