apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: {{ .Values.spec.destination.server }}
  project: default

  source:
    path: charts/prometheus
    repoURL: https://github.com/prometheus-community/helm-charts.git
    targetRevision: HEAD
    helm:
      parameters:
        - name: nodeExporter.enabled
          value: "false"
