replicaCount: 1
image:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: busybox
  type: ClusterIP
  externalPort: 80
  internalPort: 80
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi