version: "3.9"
services:
  fluentd:
    image: fluentd:v1.14-1
    container_name: fluentd
    user: root
    ports:
      - "24224:24224"
    volumes:
      - ./fluentd/fluent.conf:/fluentd/etc/fluent.conf
      - ./fluentd/entrypoint.sh:/bin/entrypoint.sh
#      - ./fluentd/fluent-plugin-s3/lib/fluent/plugin:/fluentd/plugins
#      - ./fluentd/fluent-plugin-s3/lib/fluent/log-ext.rb:/fluentd/plugins/fluentd/log-ext.rb

  spring-petclinic:
    build:
      context: ./
      dockerfile: spring-petclinic.Dockerfile
    container_name: spring-petclinic
    ports:
      - "${APP_PORT:-8080}:8080"
    depends_on:
      - fluentd

  spring-webflow-samples:
    image: maven:3.8.6-eclipse-temurin-17
    container_name: spring-hotel
    working_dir: /spring-webflow-samples/booking-mvc
    entrypoint: ["mvn", "jetty:run"]
    logging:
      driver: fluentd
      options:
        fluentd-address: 'localhost:24224'
        fluentd-async: 'true'
        fluentd-retry-wait: '5s' # r * 1.5 ^(N-1) . r: this value, N : the number of retries. See https://github.com/fluent/fluent-logger-golang/tree/master#bufferlimit
        fluentd-max-retries: '13'
        fluentd-buffer-limit: '8192'
    links:
      - fluentd
    ports:
      - "8081:8080"
    depends_on:
      - fluentd
    volumes:
      - ./spring-webflow-samples:/spring-webflow-samples
      - ~/.m2/:/root/.m2