name: Sync to CodeCommit
on: [push]
jobs:
  Sync-to-CodeCommit:
    runs-on: [self-hosted, linux, ec2-runner-dev]
    steps:
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "[INFO]Runner| ${{ runner.name }} - ${{ runner.os }} - ${{ runner.arch }}"
      - name: Git origin repo authentication
        run: |
          touch ~/.git-credentials
          echo "https://${{ secrets.origin_github_user }}:${{ secrets.origin_github_token }}@github.com" > ~/.git-credentials
          git config --global credential.https://github.com.helper store
      - name: Before Clone
        run: rm -rf *
      - name: Git Clone
        run: git clone --mirror https://${{ secrets.origin_github_user }}@github.com/${{ github.repository }}.git .
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: AWS Configuration
        run: |
          aws configure set region ${{ secrets.downstream_aws_region }} --profile ${{ secrets.downstream_aws_profile }}
          aws configure set credential_source Ec2InstanceMetadata --profile ${{ secrets.downstream_aws_profile }}
      - name: Git downstream repo Authentication for CodeCommit (aws profile needed)
        run: |
          git config --global credential.https://${{ secrets.downstream_git_remote_host }}.helper '!aws --profile ${{ secrets.downstream_aws_profile }} codecommit credential-helper $@'
          git config --global credential.https://${{ secrets.downstream_git_remote_host }}.UseHttpPath true
          git config --global http.postBuffer 52428800
      - name: Add git remote downstream
        run: git remote add downstream "https://${{ secrets.downstream_git_remote_host }}/${{ secrets.downstream_git_repository_path }}"
      - name: Git mirror to downstream
        run: git push downstream --mirror
      - name: Clean work repo
        run: |
          rm ~/.git-credentials
      - run: echo "🍏 This job's status is ${{ job.status }}."
